format = "[░▒▓](peach)$os[](fg:peach bg:yellow)$directory[](fg:yellow bg:lavender)$git_branch$git_status[](fg:lavender bg:surface1)$nodejs$rust$golang$php$git_metrics[](fg:surface1 bg:surface0)$time[\n](fg:surface0)$character"
palette = "catppuccin_mocha"
[directory]
format = "[ $path ]($style)"
style = "fg:surface0 bg:yellow"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"/media/Hdd" = "…/󱛟 "
"/pers" = " "
Documents = "󰈙 "
Downloads = " "
Music = " "
Pictures = " "
home = "󰚡 "

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "fg:surface1 bg:lavender"
symbol = ""

[git_metrics]
added_style = "fg:green bg:surface1"
deleted_style = "fg:red bg:surface1"
disabled = false
format = "[ \\(](fg:text bg:surface1)([+$added]($added_style))[/](fg:text bg:surface1)([-$deleted]($deleted_style)[\\) ](fg:text bg:surface1))"
only_nonzero_diffs = false

[git_status]
format = "[($all_status$ahead_behind )]($style)"
style = "fg:surface1 bg:lavender"

[golang]
format = "[ $symbol ($version) ]($style)"
style = "fg:text bg:surface1"
symbol = ""

[nodejs]
format = "[ $symbol ($version) ]($style)"
style = "fg:text bg:surface1"
symbol = ""

[os]
disabled = false
format = "[ $symbol](fg:base bg:peach)"

[os.symbols]
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = ""
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
RockyLinux = " "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
openSUSE = " "

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[php]
format = "[ $symbol ($version) ]($style)"
style = "fg:text bg:surface1"
symbol = ""

[rust]
format = "[ $symbol ($version) ]($style)"
style = "fg:text bg:surface1"
symbol = ""

[time]
disabled = false
format = "[  $time ]($style)"
style = "fg:text bg:surface0"
time_format = "%R"
