// Generated by Home Manager.

user_pref("app.shield.optoutstudies.enabled", false);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.bookmarks.file", "/nix/store/ip1ca3daypfr2c4vsnhx36q54j378sk8-firefox-bookmarks.html");
user_pref("browser.discovery.enabled", false);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.showSponsoredTopSites", false);
user_pref("browser.places.importBookmarksHTML", true);
user_pref("browser.preferences.defaultPerformanecSettings.enabled", false);
user_pref("browser.search.suggest.enabled.private", true);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", false);
user_pref("browser.urlbar.suggest.quicksuggest.sponsored", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.pocket.enabled", false);
user_pref("geo.enabled", false);
user_pref("gfx.webrender.all", true);
user_pref("gfx.x11-egl.force-enabled", true);
user_pref("media.ffmpeg.vaapi.enabled", true);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("privacy.firstparty.isolate", true);
user_pref("privacy.globalprivacycontrol.enabled", true);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("signon.rememberSignons", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);



